### Load in NumPy (remember to pip install numpy first)

In [ ]:
pip install numpy

In [2]:
import numpy as np

Python lists are essentially an array of pointers, each pointing to a location that contains the information related to the element. This adds a lot of overhead in terms of memory and computation. And most of this information is rendered redundant when all the objects stored in the list are of the same type!

To overcome this problem, we use NumPy arrays that contain only homogeneous elements, i.e. elements having the same data type. This makes it more efficient at storing and manipulating the array. This difference becomes apparent when the array has a large number of elements, say thousands or millions. Also, with NumPy arrays, you can perform element-wise operations, something which is not possible using Python lists!

In [ ]:
# how to initialise an array
a = np.array([23,45,67])
print(type(a))

In [ ]:
a = np.array([1,2,3,4])
b = np.array([4,2,3,1])
print(a*b)

### The Basics

In [ ]:
a = np.array([1,2,3], dtype='int16')
print(type(a))
print(type(a[0]))
print(a)

In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

In [ ]:
# Get Dimension
a.ndim
b.ndim

In [ ]:
# Get Shape # gives rows & columns
b.shape

In [ ]:
# Get Type
a.dtype

In [ ]:
# Get Size # gives bytes
a.itemsize

In [ ]:
# Get total size
a.nbytes

In [ ]:
# Get number of elements
a.size

### Accessing/Changing specific elements, rows, columns, etc

In [3]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
# Get rows & columns
a.shape

(2, 7)

In [9]:
# Get a specific element [r, c]
# I am grabbing element from 2nd row & 7th column

a[1, -1]

14

In [ ]:
# Get a specific row 
a[0,:]

In [ ]:
# Get a specific column
a[:, 4]

In [ ]:
print(a)

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

In [ ]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

In [10]:
# reshaping array
a.reshape(7,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [11]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


*3-d example

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

In [ ]:
# Get specific element
b[1,0,1]

In [ ]:
b[:,0,:]

In [ ]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [ ]:
b

### Initializing Different Types of Arrays

In [4]:
# All 0s matrix
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [8]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.31661513, 0.1586571 ],
       [0.38352682, 0.55224784],
       [0.9870269 , 0.80432952],
       [0.38390069, 0.76443271]])

In [9]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 0, -1, -1],
       [ 1, -3, -4],
       [ 5,  3,  6]])

In [11]:
# The identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Mathematics

In [12]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [13]:
a + 2

array([3, 4, 5, 6])

In [14]:
print(a)

[1 2 3 4]


In [15]:
a - 2

array([-1,  0,  1,  2])

In [16]:
a * 2

array([2, 4, 6, 8])

In [17]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [18]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [19]:
a ** 2

array([ 1,  4,  9, 16])

In [20]:
a

array([1, 2, 3, 4])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [21]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
b = np.full((3,2), 3)
print(b)

[[3 3]
 [3 3]
 [3 3]]


In [25]:
np.matmul(a,b)

array([[9., 9.],
       [9., 9.]])

In [29]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

##### Statistics

In [31]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.min(stats,axis=1)

array([1, 4])

In [35]:
np.max(stats)

6

In [36]:
np.sum(stats)

21